Eekottu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Shop.urls'),name='Shop'),
    path('user/',include('userauth.urls'),name='userauth'),
    path('vendor/',include('Vendor.urls'),name='vendor'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from Shop import views

app_name= 'Shop'

urlpatterns=[
    path('',views.index, name='index'),
    path('<str:name>/',views.shop, name="shop"),
    path('<str:category_name>/<str:sub_category_name>/<str:product_id>/', views.single_product, name='product'),
    
]

Shop/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from userauth.models import User
from django.utils.timezone import now

from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


STATUS_CHOICE={
    ("process","Processing"),
    ("shipped","Shipped"),
    ("delivered","Delivered"),
}
STATUS ={
    ("draft","Drafts"),
    ("disabled","Disabled"),
    ("in_review","In Review"),
    ("rejected","Rejected"),
    ("published","Published"),
}
RATING ={
    (1,"★✰✰✰✰"),
    (2,"★★☆☆☆"),
    (3,"★★★☆☆"),
    (4,"★★★★☆"),
    (5,"★★★★★"),
}
VENDOR_STATUS = {
        ('In Review', 'In Review'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    }




def user_directory_path(instance, filename):
    
    return 'user_{0}/{1}'.format(instance.user.id, filename)



class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=13, prefix="CAT", alphabet="ABCDEF123456789")
    name= models.CharField(max_length=100)
    icon= models.ImageField(upload_to='category')
    
    class Meta:
        verbose_name_plural = "Categories"
        
    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50"></img>'%{self.icon.url})
    
    def __str__(self):
        return self.name
    

class SubCategory(models.Model):
    scid = ShortUUIDField(unique=True, length=10, max_length=14, prefix="SCAT", alphabet="ABCDEF123456789")
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategories')

    class Meta:
        verbose_name_plural = "SubCategories"

    def __str__(self):
        return self.name
    
class Tags(models.Model):
    pass
    
class Vendor(models.Model):
    vid=ShortUUIDField(unique=True, length=10, max_length=13, prefix="VEN", alphabet="ABCDEF123456789")
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    
    name= models.CharField(max_length=100)
    image= models.ImageField(upload_to='user_img')
    
    business_name = models.CharField(max_length=255)
    description=models.TextField(null=True)
    address=models.CharField(max_length=100, default="123 main street")
    contact=models.CharField(max_length=100, unique=True,default="+91 9876543210")
    
    pan_number = models.CharField(max_length=10, unique=True)
    gst_number = models.CharField(max_length=15, unique=True)
    
    
    chat_resp_time=models.CharField(max_length=100, default="100")
    shipping_on_time=models.CharField(max_length=100, default="100")
    authentic_rating=models.CharField(max_length=100, default="100")
    days_return=models.CharField(max_length=100, default="100")
    warranty_period=models.CharField(max_length=100, default="100")
    
    terms_accepted = models.BooleanField(default=False)
    
    Vendor_status = models.CharField(choices=VENDOR_STATUS, max_length=20, default='In Review')
    
    
    
    class Meta:
        verbose_name_plural = "Vendors"
        
    def vendor_image(self):
        return mark_safe('<img src="%s" width="50" height="50"></img>'%{self.image.url})
    
    def __str__(self):
        return self.name


            


class Customer(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=13, prefix="CUST", alphabet="ABCDEF123456789")
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name= models.CharField(max_length=100)
    image= models.ImageField(upload_to=user_directory_path)
    # Add any customer-specific fields here

    class Meta:
        verbose_name_plural = "Customers"

    def __str__(self):
        return self.user.username


    
class Product(models.Model):
    
    pid=ShortUUIDField(unique=True, length=10, max_length=13, alphabet="ABCDEF123456789")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.SET_NULL, null=True)
    
    
    name= models.CharField(max_length=100)
    image= models.ImageField(upload_to=user_directory_path)
    business_name = models.CharField(max_length=255)
    description=models.TextField()
    
    price= models.DecimalField(max_digits=10, decimal_places=2,default="1.99")
    mrp_price= models.DecimalField(max_digits=10, decimal_places=2,default="3.00")
    
    specifications= models.TextField(null=True, blank =True)
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    net_quantity = models.CharField(max_length=100)
    item_weight = models.CharField(max_length=100)
    item_dimension = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    importer = models.CharField(max_length=100)
    generic_name = models.CharField(max_length=100)
    country_of_origin = models.CharField(max_length=100)
    tags = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True, blank=True)
    
    product_status = models.CharField(choices=STATUS, max_length=10)
    
    status = models.BooleanField(default=True)
    stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    
    sku=ShortUUIDField(unique=True, length=5, max_length=10,prefix="SKU", alphabet="ABCDEF123456789")
    
    
    created_at = models.DateTimeField(default=now, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False, null=True, blank=True)
    
    
    class Meta:
        verbose_name_plural = "Products"
        
    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50"></img>'%{self.image.url})
    
    def __str__(self):
        return self.name
    
    def get_percentage(self):
        new_price=(self.price/self.mrp_price)*100
        
        return new_price
    
class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    images=models.ImageField(upload_to="product_images")
    created_at = models.DateTimeField(default=now, editable=False)
    
    class Meta:
        verbose_name_plural = "Product Images"
        
    
        

class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price= models.DecimalField(max_digits=10, decimal_places=2,default="1.99")
    paid_status=models.BooleanField(default=False)
    order_date =models.DateTimeField(default=now, editable=False)
    product_status = models.CharField(choices=STATUS_CHOICE, max_length=10, default="processing")
    
    class Meta:
        verbose_name_plural = "Cart Order"
        

class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length=16)
    product_status = models.CharField( max_length=200)
    item= models.CharField(max_length=200)
    image= models.CharField(max_length=200)
    quantity= models.IntegerField(default=0)
    price= models.DecimalField(max_digits=10, decimal_places=2,default="1.99")
    total= models.DecimalField(max_digits=10, decimal_places=2,default="1.99")
    
    class Meta:
        verbose_name_plural = "Cart Order Items"
        
    def order_image(self):
        return mark_safe('<img src="/media/%s" width="50" height="50"></img>'%{self.image.url})
    

class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    review = models.TextField()
    rating= models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(default=now, editable=False)
    
    class Meta:
        verbose_name_plural = "Product Reviews"
        
    def __str__(self):
        return self.product.name
    
    def get_rating(self):
        return self.rating
    
    
class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(default=now, editable=False)
    
    class Meta:
        verbose_name_plural = "Wishlist"
        
    def __str__(self):
        return self.product.name
    

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    address= models.TextField( null=True)
    status= models.BooleanField(default=False)
    
    class Meta:
        verbose_name_plural = "Address"
    

Shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, CartOrder, CartOrderItems, Category, SubCategory, Wishlist, Vendor, ProductImages, ProductReview, Address, Customer

# Create your views here.

from collections import OrderedDict


def index(request):
    # Get all categories
    categories = Category.objects.all().order_by('name')

    products = Product.objects.order_by('brand', '-created_at')
    
    # Initialize a dictionary to store the newly added brands and their products
    newly_arrived_brands = OrderedDict()

    # Loop through the products to filter the newly added brands
    for product in products:
        # Add the product to the newly_arrived_brands dictionary using the brand as the key
        newly_arrived_brands[product.brand] = product
        
        # If the count of newly_arrived_brands exceeds 10, remove the oldest brand
        if len(newly_arrived_brands) > 10:
            oldest_brand = next(iter(newly_arrived_brands.keys()))
            newly_arrived_brands.pop(oldest_brand)

    # Convert the dictionary values to a list to pass to the template
    newly_arrived_brands_list = list(newly_arrived_brands.values())

    context = {
        'categories': categories,
        'newly_arrived_brands': newly_arrived_brands_list,
    }

    return render(request, 'Eekottu/index.html', context)

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def shop(request, name):
    
    category = Category.objects.get(name=name)
    subcategories = SubCategory.objects.filter(category=category)
    
    if request.user.is_authenticated and request.user.is_vendor:
        
        products = Product.objects.filter(category=category).exclude(user=request.user)
        
    else:
        products = Product.objects.filter(category=category)
    
    paginator = Paginator(products, 9)
    page_number = request.GET.get('page')
    products_page = paginator.get_page(page_number)
    
    context={
        'category':category,
        'subcategories': subcategories,
        'products': products_page,
    }
    
    return render(request, 'Eekottu/shop.html', context)

def single_product(request,category_name, sub_category_name, product_id):
    
    product = get_object_or_404(Product, 
                                category__name__iexact=category_name,
                                sub_category__name__iexact=sub_category_name,
                                pid=product_id)
    
    context={
        'product': product,
    }
    
    return render(request,"Eekottu/single_product.html", context)

templates/Eekottu/cart.html
{% extends 'Eekottu/base.html'%}
{% load static %}


{% block title %}Welcome to Eekottu{% endblock title %}
{%load humanize%}

{% block container %}


    <section class="py-5 mb-5" style="background: url(images/background-pattern.jpg);">
      <div class="container-fluid">
        <div class="d-flex justify-content-between">
          <h1 class="page-title pb-2">Cart</h1>
          <nav class="breadcrumb fs-6">
            <a class="breadcrumb-item nav-link" href="#">Home</a>
            <a class="breadcrumb-item nav-link" href="#">{{user.username}}'s</a>
            <span class="breadcrumb-item active" aria-current="page">Cart</span>
          </nav>
        </div>
      </div>
    </section>

    <section class="shopify-cart padding-large">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-8">
            <div class="cart-table">
              <div class="cart-header">
                <div class="row d-flex">
                  <h6 class="cart-title text-uppercase text-muted col-lg-4 pb-3">Product</h6>
                  <h6 class="cart-title text-uppercase text-muted col-lg-3 pb-3">Quantity</h6>
                  <h6 class="cart-title text-uppercase text-muted col-lg-4 pb-3">Subtotal</h6>
                </div>
              </div>
              {% for cart_item in cart_items %}
              <div class="cart-item border-top border-bottom">
                <div class="row align-items-center"> 
                  <div class="col-lg-4 col-md-3">
                    <div class="cart-info d-flex flex-wrap align-items-center mb-4">
                      <div class="col-lg-5">
                        <div class="card-image">
                          <img src="{{ cart_item.product.image.url }}" alt="cloth" class="img-fluid">
                        </div>
                      </div>
                      <div class="col-lg-7">
                        <div class="card-detail ps-3">
                          <h5 class="card-title">
                            <a href="#" class="text-decoration-none">{{cart_item.product}}</a>
                          </h5>
                          <div class="card-price">
                            <span class="money text-dark" data-currency-inr="{{cart_item.product.price}}">₹ {{cart_item.product.price|intcomma}}</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-7">
                    <div class="row d-flex">
                      <div class="col-md-4">
                        <div class="input-group product-qty">
                          <span class="input-group-btn">
                              <button type="button" class="quantity-left-minus btn btn-light btn-number" data-type="minus" data-field="">
                                <svg width="16" height="16"><use xlink:href="#minus"></use></svg>
                              </button>
                          </span>
                          <input type="text" id="quantity" name="quantity" class="form-control input-number text-center" value="{{cart_item.quantity}}" min="1" max="100">
                          <span class="input-group-btn">
                              <button type="button" class="quantity-right-plus btn btn-light btn-number" data-type="plus" data-field="">
                                  <svg width="16" height="16"><use xlink:href="#plus"></use></svg>
                              </button>
                          </span>
                        </div>
                      </div>
                      <div class="col-md-8 text-center">
                        <div class="total-price">
                          <span class="money text-dark">₹ {{cart_item.product.price|intcomma}}</span>
                        </div>
                      </div>   
                    </div>             
                  </div>
                  <div class="col-lg-1 col-md-2">
                    <div class="cart-remove">
                      <a href="{% url 'Customer:remove_from_cart' cart_item.product.pk %}">
                        <svg width="32px">
                          <use xlink:href="#trash"></use>
                        </svg>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              {% empty %}
              <p>Your cart is empty.</p>
              {% endfor %}
            </div>
          </div>
          <div class="col-md-4">
            <div class="cart-totals bg-grey padding-medium">
              <h4 class="text-dark pb-4">Cart Total</h4>
              <div class="total-price pb-5">
                <table cellspacing="0" class="table text-uppercase">
                  <tbody>
                    <tr class="subtotal pt-2 pb-2 border-top border-bottom">
                      <th>Subtotal</th>
                      <td data-title="Subtotal">
                        <span class="price-amount amount text-dark ps-5">
                          <bdi>
                            <span class="price-currency-symbol">₹</span>{{ total_price|intcomma }}
                          </bdi>
                        </span>
                      </td>
                    </tr>
                    <tr class="order-total pt-2 pb-2 border-bottom">
                      <th>Total</th>
                      <td data-title="Total">
                        <span class="price-amount amount text-dark ps-5">
                          <bdi>
                            <span class="price-currency-symbol">₹</span>{{ total_price|intcomma }}
                          </bdi>
                        </span>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div class="button-wrap row g-2">
                <div class="col-md-6"><button class="btn btn-dark btn-lg text-uppercase btn-rounded-none w-100">Update Cart</button></div>
                <div class="col-md-6"><button class="btn btn-dark btn-lg text-uppercase btn-rounded-none w-100">Continue Shopping</button></div>
                <div class="col-md-12"><button class="btn btn-primary btn-lg text-uppercase btn-rounded-none w-100"><a href="{% url 'Eekottu:checkout' %}?total_price={{ total_price }}">Proceed to checkout</a></button></div>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </section> 
    

    

  
    {% endblock %}

templates/Eekottu/shop.html
{% extends 'Eekottu/base.html'%}
{% load static %}


{% block title %}Welcome to Eekottu{% endblock title %}
{% load humanize %}

{% block container %}




    <section class="py-5 mb-5" style="background: url({% static '/assets/images/background-pattern.jpg'%});">
      <div class="container-fluid">
        <div class="d-flex justify-content-between">
          <h1 class="page-title pb-2">Shop</h1>
          <nav class="breadcrumb fs-6">
            <a class="breadcrumb-item nav-link" href="{% url 'Shop:index' %}">Home</a>
            <a class="breadcrumb-item nav-link" href="{% url 'Shop:shop' category.name %}">{{category.name}}</a>
            <span class="breadcrumb-item active" aria-current="page">Shop</span>
          </nav>
        </div>
      </div>
    </section>

    <div class="shopify-grid">
      <div class="container-fluid">
        <div class="row">
          <aside class="col-md-3">
            <div class="sidebar">
              <div class="widget-menu">
                <div class="widget-search-bar pe-5">
                  <form role="search" method="get" class="d-flex">
                    
                      <input class="form-control form-control-lg rounded-start rounded-0 bg-light" type="email" placeholder="What are you looking for?" aria-label="What are you looking for?">
                      <button class="btn btn-dark rounded-end rounded-0" type="submit">Search</button>
                    </form>
                  
                </div> 
              </div>
              <div class="widget-product-categories pt-5">
                <h5 class="widget-title">Categories</h5>
                <ul class="product-categories sidebar-list list-unstyled">
                  <li class="cat-item">
                    <a href="">All</a>
                  </li>
                  {% for subcategory in subcategories %}
                  <li class="cat-item">
                    <a href="#" class="nav-link">{{subcategory.name}}</a>
                  </li>
                  {%endfor%}
                </ul>
              </div>
              <div class="widget-product-tags pt-3">
                <h5 class="widget-title">Tags</h5>
                <ul class="product-tags sidebar-list list-unstyled">
                  {% for product in products %}
                  <li class="tags-item">
                    <a href="#" class="nav-link">{{product.generic_name}}</a>
                  </li>
                  {%endfor%}
                </ul>
              </div>
              <div class="widget-product-brands pt-3">
                <h5 class="widget-title">Brands</h5>
                <ul class="product-tags sidebar-list list-unstyled">
                  {% for product in products %}
                  <li class="tags-item">
                    <a href="#" class="nav-link">{{product.brand}}</a>
                  </li>
                  {%endfor%}
                </ul>
              </div>
              <div class="widget-price-filter pt-3">
                <h5 class="widget-titlewidget-title">Filter By Price</h5>
                <ul class="product-tags sidebar-list list-unstyled">
                  <li class="tags-item">
                    <a href="#" class="nav-link">Less than $10</a>
                  </li>
                  
                </ul>
              </div>
            </div>
          </aside>

          <main class="col-md-9">
            <div class="filter-shop d-flex justify-content-between">
              <div class="showing-product">
                <p>Showing {{ products.start_index }}–{{ products.end_index }} of {{ products.paginator.count }} results</p>
              </div>
              
              
              <div class="sort-by">
                <select id="input-sort" class="form-control" data-filter-sort="" data-filter-order="">
                  <option value="">Default sorting</option>
                  <option value="">Name (A - Z)</option>
                  <option value="">Name (Z - A)</option>
                  <option value="">Price (Low-High)</option>
                  <option value="">Price (High-Low)</option>
                  <option value="">Rating (Highest)</option>
                  <option value="">Rating (Lowest)</option>
                  <option value="">Model (A - Z)</option>
                  <option value="">Model (Z - A)</option>   
                </select>
              </div>
            </div>
            
            <div class="product-grid row row-cols-sm-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">

              {% for product in products %}
              <div class="col">
                <div class="product-item">
                  {% if product.id in wishlist_products %}
                  <a href="" class="btn-wishlist" id="wishlist-button-{{ product.id }}"><svg width="24" height="24"><use xlink:href="#remove"></use></svg></a>
                  {%else%}
                  <a href="" class="btn-wishlist" id="wishlist-button-{{ product.id }}"><svg width="24" height="24"><use xlink:href="#heart"></use></svg></a>
                  {%endif%}
                  <figure>
                    <a href="{% url 'Shop:product' product.category.name product.sub_category.name product.pid %}" title="Product Title">
                      <img src="{{ product.image.url }}" class="tab-image" alt="{{product.name}}">
                    </a>
                  </figure>
                  <h3>{{product.name|slice:"0:30" }}...</h3>
                  <span class="qty">{{product.net_quantity}}</span><span class="rating"><svg width="24" height="24" class="text-primary"><use xlink:href="#star-solid"></use></svg> {{product.ratings}}</span>
                  <span class="price">{{ product.price|intcomma }}</span>
                  <div class="d-flex align-items-center justify-content-between">


                  <form method="POST" action="">
                      {% csrf_token %}

                    {% if product.inventory.stock <= 0 %}
                    <p>out of Stock </p>


                    {% elif product.inventory.stock < 10 %}
                    
                    <div class="input-group product-qty">
                        <span>Only {{ product.inventory.stock }} left in stock</span>
                        <span class="input-group-btn">
                            <button type="button" class="quantity-left-minus btn btn-danger btn-number" data-type="minus" data-field="">
                              <svg width="16" height="16"><use xlink:href="#minus"></use></svg>
                            </button>
                        </span>
                        
                        
                       
                        <input type="text" id="quantity" name="quantity" class="form-control input-number" value="0" min="1" max="10">
                        
                        
                       


                        <span class="input-group-btn">
                            <button type="button" class="quantity-right-plus btn btn-success btn-number" data-type="plus" data-field="">
                                <svg width="16" height="16"><use xlink:href="#plus"></use></svg>
                            </button>
                        </span>
                    </div>
                    <button class="nav-link">Add to Cart <svg width="24" height="24"><use xlink:href="#cart"></use></svg></button>



                    {%else%}


                    <div class="input-group product-qty">
                      <span class="input-group-btn">
                          <button type="button" class="quantity-left-minus btn btn-danger btn-number" data-type="minus" data-field="">
                            <svg width="16" height="16"><use xlink:href="#minus"></use></svg>
                          </button>
                      </span>
                      
                      
                        <input type="text" id="quantity" name="quantity" class="form-control input-number" value="0" min="1" max="10">
                        
                      
                      {% comment %} <input type="text" id="quantity" name="quantity" class="form-control input-number" value="0" min="1" max="{{ product.inventory.stock }}"> {% endcomment %}

                      <span class="input-group-btn">
                          <button type="button" class="quantity-right-plus btn btn-success btn-number" data-type="plus" data-field="">
                              <svg width="16" height="16"><use xlink:href="#plus"></use></svg>
                          </button>
                      </span>
                    </div>
                  
                    <button class="nav-link" type='submit'>Add to Cart <svg width="24" height="24"><use xlink:href="#cart"></use></svg></button>
                    {% endif %}
                  </form> 
                  </div>
                </div>
              </div>
              {%endfor %}
  

            </div>
            <!-- / product-grid -->

            
<!-- Display the pagination -->
      <nav class="navigation paging-navigation text-center padding-medium" role="navigation">
        <div class="pagination loop-pagination d-flex justify-content-center align-items-center">
          {% if products.has_previous %}
            <a href="?page=1">
              <svg class="chevron-left pe-3">
                <use xlink:href="#chevron-left"></use>
              </svg>
            </a>
          {% endif %}

          {% for page_num in products.paginator.page_range %}
            {% if products.number == page_num %}
              <span aria-current="page" class="page-numbers current pe-3">{{ page_num }}</span>
            {% else %}
              <a class="page-numbers pe-3" href="?page={{ page_num }}">{{ page_num }}</a>
            {% endif %}
          {% endfor %}

          {% if products.has_next %}
            <a href="?page={{ products.paginator.num_pages }}">
              <svg class="chevron-right ps-3">
                <use xlink:href="#chevron-right"></use>
              </svg>
            </a>
          {% endif %}
        </div>
      </nav>

          </main>
          
        </div>
      </div>
    </div>



  
  
  
  

    
{% endblock %}