Eekottu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Shop.urls'),name='Shop'),
    path('user/',include('userauth.urls'),name='userauth'),
    path('vendor/',include('Vendor.urls'),name='vendor'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from Shop import views

app_name= 'Shop'

urlpatterns=[
    path('',views.index, name='index'),
    path('<str:name>/',views.shop, name="shop"),
    path('<str:category_name>/<str:sub_category_name>/<str:product_id>/', views.single_product, name='product'),
    
]

userauth/urls.py
from django.urls import path
from userauth import views

app_name= 'userauth'

urlpatterns=[
    path('register/',views.register, name='register'),
    path('activate/<str:uidb64>/<str:token>/<str:is_customer>/', views.ActivateAccountView.as_view(), name = 'activate'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('step-one/<str:uidb64>/<str:token>/<str:is_customer>/', views.StepOneView.as_view(), name='step_one'),
    path('step-two/<str:uidb64>/<str:token>/<str:is_customer>/', views.StepTwoView.as_view(), name='step_two'),
    path('step-three/<str:uidb64>/<str:token>/<str:is_customer>/', views.StepThreeView.as_view(), name='step_three'),
]

userauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    is_customer = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.username
    

userauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauth.models import User
from Shop.models import Vendor

class UserRegisterForm(UserCreationForm):
    username= forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username','class':'form-control form-control-lg'}))
    email= forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'Email','class':'form-control form-control-lg'}))
    password1= forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password','class':'form-control form-control-lg'}))
    password2= forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password','class':'form-control form-control-lg'}))
    is_customer = forms.BooleanField(required=False, label="Are you a customer?", widget=forms.RadioSelect(choices=[(True, 'Customer'), (False, 'Vendor')]))

    class Meta:
        model = User
        fields =['username','email']
        
        
class VendorStepOneForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Owner Full Name as per PAN', 'class': 'form-control form-control-lg'}), required=True)
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control form-control-lg'}),required=True)
    business_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Business Name as per GST', 'class': 'form-control form-control-lg'}),required=True)
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Brief description about the company', 'class': 'form-control form-control-lg'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Business address', 'class': 'form-control form-control-lg'}),required=True)
    contact = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Contact', 'class': 'form-control form-control-lg'}),required=True)
    pan_number = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'CMMXXXXX7', 'class': 'form-control form-control-lg'}),required=True)
    gst_number = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'CCCXXXX88XXXXX', 'class': 'form-control form-control-lg'}),required=True)
    
    class Meta:
        model = Vendor
        fields = ['name', 'image', 'business_name', 'description', 'address', 'contact', 'pan_number', 'gst_number']

class VendorStepTwoForm(forms.ModelForm):
    chat_resp_time = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Mention in Days', 'class': 'form-control form-control-lg'}), required=True)
    shipping_on_time = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Mention in Days', 'class': 'form-control form-control-lg'}),required=True)
    authentic_rating= forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Mention in Rating', 'class': 'form-control form-control-lg'}))
    days_return = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Mention in Days', 'class': 'form-control form-control-lg'}),required=True)
    warranty_period = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Mention in Months', 'class': 'form-control form-control-lg'}),required=True)
   
    class Meta:
        model = Vendor
        fields = ['chat_resp_time', 'shipping_on_time', 'authentic_rating', 'days_return', 'warranty_period']

class VendorStepThreeForm(forms.ModelForm):
    
    terms_accepted = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input','id':'terms_check'}),
        required=True
    )
    
    class Meta:
        model = Vendor
        fields = ['terms_accepted']

userauth/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.urls import reverse
from .forms import UserRegisterForm
from django.views.generic import View

from django.conf import settings
from django.core.mail import EmailMessage
from .models import User

from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from django.utils.encoding import force_bytes, force_str
from .utils import generate_token
from django.urls import reverse
from django.contrib import messages

from Shop.models import Customer, Vendor
from django.contrib.auth import login, authenticate, logout
# Create your views here.
def register(request):
    
    if request.method == 'POST':
        form=UserRegisterForm(request.POST)
        
        if form.is_valid():
            new_user=form.save(commit=False)
            new_user.is_active = False
            new_user.save()
            
            is_customer = form.cleaned_data.get('is_customer')
            
            if is_customer:
                new_user.is_customer=True
            else:
                new_user.is_vendor=True
                
            new_user.save()
                      
            username= form.cleaned_data.get("username")
            
            messages.success(request,f"Hey {username}, Kindly check your mail we sent a verification email.")
            
    
    
            email_subject = "Activate your Account"
            message = render_to_string('userauth/user_activation.html',{
            'user':new_user,
            'domain':'127.0.0.1:8000',
            'uid':urlsafe_base64_encode(force_bytes(new_user.pk)),
            'token':generate_token.make_token(new_user),
            'is_customer':'customer' if is_customer else 'vendor'
            })
            
            
            email_message = EmailMessage(
            email_subject,
            message,
            settings.EMAIL_HOST_USER,
            [new_user.email]
            
            )
            
            email_message.send()
            return redirect('Shop:index')
        else:
            messages.warning(request, form.errors)
    else:
        form=UserRegisterForm()
    
    context={
        'form':form,
    }
    
    return render(request,'userauth/registration.html', context)

from django.db import IntegrityError
class ActivateAccountView(View):
    
    def get(self, request, uidb64, token, is_customer):
        try:
            uid= force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
            
            
        except Exception as e:
            user = None
            
        print(user)
        if user is not None and generate_token.check_token(user,token):
            
            
            if is_customer == 'vendor':
                try:
                    vendor, created = Vendor.objects.get_or_create(user=user)
                    vendor.save()             
                except IntegrityError as e: 
                    print(f"IntegrityError occurred: {e}")
                     
                token=generate_token.make_token(user)
                return redirect('userauth:step_one', uidb64=uidb64, token=token, is_customer=is_customer)
                # If the user is registered as a customer, create the Customer object and save it
                
            elif is_customer == 'customer':
                customer, created = Customer.objects.get_or_create(user=user)
                if created:
                    customer.save()
                
                user.is_active=True
            
                user.save()
            
            login(request, user)
            
            messages.success(request,"Account Activated successfully")
            return redirect('Shop:index')
            
        return render(request, 'userauth/user_auth_fail.html')
    


from .forms import VendorStepOneForm, VendorStepTwoForm, VendorStepThreeForm

from django.core.exceptions import ObjectDoesNotExist

class StepOneView(View):
    def get(self, request, uidb64, token, is_customer):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        print('step=one->',user, generate_token.check_token(user, token) )
        if user is not None and is_customer == 'vendor' and generate_token.check_token(user, token):
            form = VendorStepOneForm()
            return render(request, 'vendor/step_one.html', {'form': form})
        else:
            return render(request, 'userauth/user_auth_fail.html')

    def post(self, request, uidb64, token, is_customer):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and is_customer == 'vendor' and generate_token.check_token(user, token):
            form = VendorStepOneForm(request.POST, request.FILES)
            if form.is_valid():
                try:
                    vendor = Vendor.objects.get(user=user)
                except ObjectDoesNotExist:
                    vendor = Vendor(user=user)

                
                vendor.name = form.cleaned_data['name']
                vendor.image = form.cleaned_data['image']
                vendor.business_name = form.cleaned_data['business_name']
                vendor.description = form.cleaned_data['description']
                vendor.address = form.cleaned_data['address']
                vendor.contact = form.cleaned_data['contact']
                vendor.pan_number = form.cleaned_data['pan_number']
                vendor.gst_number = form.cleaned_data['gst_number']
                vendor.save()

                token = generate_token.make_token(user)
                return redirect('userauth:step_two', uidb64=uidb64, token=token, is_customer=is_customer)
            else:
                return render(request, 'vendor/step_one.html', {'form': form})
        else:
            return render(request, 'userauth/user_auth_fail.html')


class StepTwoView(View):
    def get(self, request, uidb64, token, is_customer):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        print('step=2->',user, generate_token.check_token(user, token) )

        if user is not None and is_customer == 'vendor' and generate_token.check_token(user, token):
            form = VendorStepTwoForm()
            return render(request, 'vendor/step_two.html', {'form': form})
        else:
            return render(request, 'userauth/user_auth_fail.html')
    
    def post(self, request, uidb64, token, is_customer):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and is_customer == 'vendor' and generate_token.check_token(user, token):
            form = VendorStepTwoForm(request.POST)
            if form.is_valid():
                try:
                    vendor = Vendor.objects.get(user=user)
                except ObjectDoesNotExist:
                    return render(request, 'userauth/user_auth_fail.html')

                vendor.chat_resp_time = form.cleaned_data['chat_resp_time']
                vendor.shipping_on_time = form.cleaned_data['shipping_on_time']
                vendor.authentic_rating = form.cleaned_data['authentic_rating']
                vendor.days_return = form.cleaned_data['days_return']
                vendor.warranty_period = form.cleaned_data['warranty_period']
                vendor.save()

                token = generate_token.make_token(user)
                return redirect('userauth:step_three', uidb64=uidb64, token=token, is_customer=is_customer)
            else:
                return render(request, 'vendor/step_two.html', {'form': form})
        else:
            return render(request, 'userauth/user_auth_fail.html')


class StepThreeView(View):
    def get(self, request, uidb64, token, is_customer):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        print('step=3->',user, generate_token.check_token(user, token) )

        if user is not None and is_customer == 'vendor' and generate_token.check_token(user, token):
            form = VendorStepThreeForm()
            return render(request, 'vendor/step_three.html', {'form': form})
        else:
            return render(request, 'userauth/user_auth_fail.html')

    def post(self, request, uidb64, token, is_customer):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and is_customer == 'vendor' and generate_token.check_token(user, token):
            form = VendorStepThreeForm(request.POST)
            if form.is_valid():
                try:
                    vendor = Vendor.objects.get(user=user)
                except ObjectDoesNotExist:
                    return render(request, 'userauth/user_auth_fail.html')

                vendor.terms_accepted = form.cleaned_data['terms_accepted']
                vendor.Vendor_status = 'In Review'
                vendor.save()
                
                user.is_active=True
                user.save()
                login(request, user)

templates/userauth/password_reset_email.html
{% autoescape off %}

<p>Please click the following link to reset your password:</p>
<p><a href="{{ password_reset_url }}">Reset Password</a></p>


http://{{domain}}{% url 'authentication:vendor_password_reset_verify' uidb64=uid token=token %}


{% endautoescape %}

templates/userauth/password_reset_form.html
{% extends 'authentication/base.html'%}
{% load static %}

{% block title %}Password Reset Form{% endblock title %}

{% block login_signup %}


 <section class="py-5" style="background-image: url('static/assets/images/background-pattern.jpg');background-repeat: no-repeat;background-size: cover;">
    <div class="container-fluid">

      <div class="bg-secondary py-5 my-5 rounded-5" style="background: url('static/assets/images/bg-leaves-img-pattern.png') no-repeat;">
        <div class="container my-5">
          <div class="row">
            <div class="col-md-6 p-5">
              <div class="section-header">
                <h2 class="section-title display-4">Password Reset Form</h2>
              </div>
            </div>
            <div class="col-md-6 p-5">
              <form method="post" action="{% url 'authentication:vendor_reset_password_form' uidb64=uidb64 token=token %}">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="password" class="form-label">New Password</label>
                  <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <div class="mb-3">
                  <label for="confirm_password" class="form-label">Confirm Password</label>
                  <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
                </div>
                <button type="submit" class="btn btn-primary">Reset Password</button>
              </form>
            </div>
            
          </div>
          
        </div>
      </div>
      
    </div>
  </section>

{% endblock %}

templates/userauth/registration.html
<!-- vendor_registration.html -->
{% extends 'userauth/base.html'%}
{% load static %}

{% block title %}Registration{% endblock title %}

{% block login_signup %}



 <section class="py-5" style="background-image: url({% static '/assets/images/background-pattern.jpg'%});background-repeat: no-repeat;background-size: cover;">
    <div class="container-fluid">

      <div class="bg-secondary py-5 my-5 rounded-5" style="background: url({% static '/assets/images/bg-leaves-img-pattern.png'%}) no-repeat;">
        <div class="container my-5">
          <div class="row">
            <div class="col-md-6 p-5">
              <div class="section-header">
                <h2 class="section-title display-4">Customer Registration</h2>
              </div>
              <p>Explore the more and give the more merchedise</p>
              <div class="mb-3">
                Want to Sell? click here to <a href = ""> Register </a> as a Vendor
              </div>
              {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissable fade show" role='alert'>
                      <strong>{{message}}</strong>
                      <button type ="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
              {% endfor %}
            </div>
            <div class="col-md-6 p-5">
              <form method="POST" action="{% url 'userauth:register'%}">
                {% csrf_token %}

                
                <div class="mb-3">
                  <label for="username" class="form-label">Username</label>
                  {{form.username}}
                </div>
                <div class="mb-3">
                  <label for="email" class="form-label">Email</label>
                  {{form.email}}
                </div>
                <div class="mb-3">
                  <label for="password1" class="form-label">Password</label>
                  <div class="input-group">
                      {{ form.password1 }}
                      <button type="button" class="btn btn-outline-secondary input-group-text" id="togglePassword1">
                          <i class="bi bi-eye" id="eye-icon1"></i>
                      </button>
                  </div>
              </div>
              <div class="mb-3">
                  <label for="password2" class="form-label">Confirm Password</label>
                  <div class="input-group">
                      {{ form.password2 }}
                      <button type="button" class="btn btn-outline-secondary input-group-text" id="togglePassword2">
                          <i class="bi bi-eye" id="eye-icon2"></i>
                      </button>
                  </div>
              </div>
                <div class="mb-3">
                  <label class="form-label">Are you registered as a:</label>
                  
                  <span>{{ form.is_customer }}</span>
                  
                  <span>{{ form.is_vendor }}</span>
              </div>
                <div class="d-grid gap-2">
                  <button type="submit" class="btn btn-dark btn-lg">Register</button>
                </div>
              </form>
              <div class="mb-3">
                Already a User? click here to <a href = ""> login </a>
              </div>
              
            </div>
            
          </div>
          
        </div>
      </div>
      
    </div>
  </section>

  {% endblock login_signup %}

templates/userauth/user_activation.html
{% autoescape off %}


Hi {{user.username}},

please click the link  below to verify your  account


http://{{domain}}{% url 'userauth:activate' uidb64=uid token=token is_customer=is_customer%}



{% endautoescape %}

templates/userauth/user_auth_fail.html
{% extends 'userauth/base.html'%}
{% load static %}

{% block title %}Error{% endblock title %}

{% block login_signup %}


<div class="bg-secondary py-5 my-5 rounded-5" style="background: url({% static '/assets/images/background-pattern.jpg'%}) no-repeat;">
    <div class="container my-5">
      <div class="row">
        <div class="col-md-12 p-5">
            <div class="section-header">
                <h2 class="section-title display-4">Something Went Wrong</h2>
            </div>
        </div>
            
    </div>
    
  </div>
</div>

{% endblock login_signup%}

templates/userauth/user_login.html
{% extends 'userauth/base.html'%}
{% load static %}

{% block title %}Login{% endblock title %}

{% block login_signup %}


 <section class="py-5" style="background-image: url({% static '/assets/images/background-pattern.jpg'%});background-repeat: no-repeat;background-size: cover;">
    <div class="container-fluid">

      <div class="bg-secondary py-5 my-5 rounded-5" style="background: url({% static '/assets/images/bg-leaves-img-pattern.png'%}) no-repeat;">
        <div class="container my-5">
          <div class="row">
            <div class="col-md-6 p-5">
              <div class="section-header">
                <h2 class="section-title display-4">User Login</h2>
              </div>
              <p>Explore the more and give the more merchedise</p>
              {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissable fade show" role='alert'>
                      <strong>{{message}}</strong>
                      <button type ="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
              {% endfor %}
            </div>
            <div class="col-md-6 p-5">
              <form method="POST" action="">
                {% csrf_token %}

                <div class="mb-3">
                  <label for="email" class="form-label">Email</label>
                  <input type="text"
                    class="form-control form-control-lg" name="email" id="email" placeholder="Email">
                </div>
                <div class="mb-3">
                  <label for="password" class="form-label">Password</label>
                  <input type="password" class="form-control form-control-lg" name="password" id="password" placeholder="Enter ur Password">
                </div>
                
                <div class="d-grid gap-2">
                  <button type="submit" class="btn btn-dark btn-lg">Login</button>
                </div>
                <div class=" mb-3">
                  New User ? click here to <a href = "{% url 'userauth:register'%}">register</a>
                </div>
                <div class=" mb-3">
                  Forgot Password ? click here to <a href = "">reset</a>
                </div>
              </form>
              
            </div>
            
          </div>
          
        </div>
      </div>
      
    </div>
  </section>

{% endblock login_signup %}

templates/userauth/vendor_forgot_password.html
{% extends 'authentication/base.html'%}
{% load static %}

{% block title %}Login{% endblock title %}

{% block login_signup %}


 <section class="py-5" style="background-image: url({% static '/assets/images/background-pattern.jpg'%});background-repeat: no-repeat;background-size: cover;">
    <div class="container-fluid">

      <div class="bg-secondary py-5 my-5 rounded-5" style="background: url({% static '/assets/images/bg-leaves-img-pattern.png'%}) no-repeat;">
        <div class="container my-5">
          <div class="row">
            <div class="col-md-6 p-5">
              <div class="section-header">
                <h2 class="section-title display-4">Forgot Password ?</h2>
              </div>
              <h6>Enter register email to get password reset link</h6>
            </div>
            <div class="col-md-6 p-5">
              <form method="post" action="{% url 'authentication:vendor_forgot_password' %}">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="email" class="form-label">Email</label>
                  <input type="email" class="form-control" id="email" name="email" required>
                </div>
                <button type="submit" class="btn btn-primary">Reset Password</button>
              </form>
            </div>
            
          </div>
          
        </div>
      </div>
      
    </div>
  </section>

{% endblock %}